### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by mlavin** [caktus/rapidsms-twilio#12]
This project has been stable for a long time. In usually only needs minor updates for Django or RapidSMS changes. We should get this up to date with the latest and call it 1.0. Need to determine what versions we are going to support.

- [x] Determine supported Python versions
- [x] Determine supported Django versions
- [x] Determine supported RapidSMS versions
- [x] Determine resolution for #8.
- [x] Document future release cycles for new Django/RapidSMS versions

Did I miss anything?

**Comment by mlavin** [comment]
My votes:

- Python 2.7, 3.3+
- Django 1.7, 1.8. No pending deprecations when running 1.8.
- RapidSMS 0.18, 0.19. These are the first versions to support 1.7.

Future releases would loosely follow Django's release cycle. i.e 1.1 would be release to ensure 1.9 support with no pending deprecations.

**Comment by mlavin** [comment]
Note RapidSMS does not yet support Python 3.3 but assuming that lands reasonably soon then this should work with that release (0.20 or whatever it is called) as well.

**Comment by mlavin** [comment]
Dropping 1.6 support means not having to deal with both South and Django migrations. 1.6 is also dropping out of support next month with the upcoming 1.8 release.

**Comment by vkurup** [comment]
I think we're in good shape for a 1.0 release, what do you think?

**Comment by mlavin** [comment]
Code-wise yes. The only thing that I think would be good is a clear plan for supported Django and RapidSMS versions going forward.

**Comment by vkurup** [comment]
Oh yeah. I agree with your recommendation above that future releases loosely follow Django's release cycle. RapidSMS releases aren't that organized yet, so I don't think it makes sense to say anything about them yet. Maybe with the next RapidSMS release, we can try to start having RapidSMS follow Django as well.

**Comment by vkurup** [comment]
This has been now completed, and a 1.0.0 release is tagged on github. It just needs to be uploaded to PyPI. I don't have PyPI access for this package.

**Comment by mlavin** [comment]
Added you as a maintainer.

**Comment by vkurup** [comment]
Thanks, uploaded!
